export const ACTION_VERBS = [
  'achieved',
  'accelerated',
  'advanced',
  'advised',
  'advocated',
  'analyzed',
  'architected',
  'assembled',
  'authored',
  'automated',
  'built',
  'boosted',
  'brokered',
  'calibrated',
  'captained',
  'chaired',
  'championed',
  'charted',
  'coached',
  'collaborated',
  'communicated',
  'completed',
  'conceived',
  'conducted',
  'consolidated',
  'constructed',
  'consulted',
  'coordinated',
  'created',
  'cultivated',
  'debugged',
  'decreased',
  'delivered',
  'demonstrated',
  'designed',
  'developed',
  'devised',
  'directed',
  'documented',
  'doubled',
  'drafted',
  'drove',
  'earned',
  'edited',
  'eliminated',
  'engineered',
  'established',
  'evaluated',
  'executed',
  'expanded',
  'expedited',
  'facilitated',
  'founded',
  'generated',
  'grew',
  'guided',
  'headed',
  'helped',
  'identified',
  'implemented',
  'improved',
  'inaugurated',
  'increased',
  'influenced',
  'initiated',
  'innovated',
  'inspected',
  'installed',
  'instituted',
  'instructed',
  'integrated',
  'interviewed',
  'launched',
  'led',
  'managed',
  'mastered',
  'mentored',
  'modeled',
  'moderated',
  'monitored',
  'negotiated',
  'obtained',
  'operated',
  'optimized',
  'orchestrated',
  'organized',
  'originated',
  'overhauled',
  'oversaw',
  'performed',
  'pioneered',
  'planned',
  'presented',
  'produced',
  'programmed',
  'promoted',
  'proposed',
  'prototyped',
  'published',
  'raised',
  'recruited',
  'redesigned',
  'reduced',
  'refined',
  'reorganized',
  'replaced',
  'researched',
  'resolved',
  'revamped',
  'reversed',
  'revitalized',
  'saved',
  'scheduled',
  'secured',
  'spearheaded',
  'standardized',
  'streamlined',
  'strengthened',
  'structured',
  'succeeded',
  'supervised',
  'supported',
  'surveyed',
  'taught',
  'tested',
  'trained',
  'transformed',
  'translated',
  'troubleshot',
  'tutored',
  'upgraded',
  'volunteered',
  'won',
] as const;

export const POWER_WORDS = ACTION_VERBS;

const REGEX_SPECIAL_CHARS = /[.*+?^${}()|[\]\\]/g;
const escapeRegExp = (value: string) => value.replace(REGEX_SPECIAL_CHARS, '\\$&');
const powerWordsPattern = POWER_WORDS.map(escapeRegExp).join('|');

export const POWER_VERB_PATTERN = new RegExp(`\\b(${powerWordsPattern})\\b`, 'i');
export const POWER_VERB_GLOBAL_PATTERN = new RegExp(`\\b(${powerWordsPattern})\\b`, 'gi');
export const POWER_VERB_START_PATTERN = new RegExp(`^(${powerWordsPattern})\\b`, 'i');

/**
 * Boundary-aware term matching. Uses non-alphanumeric boundaries so short
 * terms like "r" or "go" only match as standalone tokens, and terms with
 * punctuation like "c++" or "next.js" still match.
 */
export function matchesTerm(text: string, term: string): boolean {
  const pattern = new RegExp(`(?:^|[^a-z0-9])${escapeRegExp(term)}(?:$|[^a-z0-9])`, 'i');
  return pattern.test(text);
}

// Verb strength tiers. A verb belongs to exactly one tier: weak verbs signal
// involvement without ownership, strong verbs signal ownership of an outcome,
// and everything else in ACTION_VERBS is medium. "Managed" is a normal,
// serviceable verb: medium, never penalized.
export const POWER_VERBS_WEAK = [
  'helped',
  'supported',
  'assisted',
  'participated',
  'worked',
  'involved',
  'handled',
  'performed',
  'responsible',
  'aided',
];

// Every entry here also appears in ACTION_VERBS, so each one is extractable
// by seedFields and countable by the strong-verb metrics.
export const POWER_VERBS_STRONG = [
  'architected',
  'spearheaded',
  'pioneered',
  'transformed',
  'accelerated',
  'championed',
  'orchestrated',
  'optimized',
  'engineered',
  'overhauled',
  'automated',
  'launched',
  'founded',
  'eliminated',
  'doubled',
];

export function getVerbStrength(verb: string): 'weak' | 'medium' | 'strong' {
  const lower = verb.trim().toLowerCase();
  if (POWER_VERBS_STRONG.includes(lower)) return 'strong';
  if (POWER_VERBS_WEAK.includes(lower)) return 'weak';
  return 'medium';
}

export function suggestStrongerVerb(weakVerb: string): string {
  const suggestions: Record<string, string> = {
    helped: 'Enabled',
    supported: 'Championed',
    managed: 'Led',
    worked: 'Built',
    handled: 'Resolved',
    performed: 'Delivered',
    assisted: 'Partnered',
    participated: 'Contributed',
    involved: 'Drove',
    aided: 'Guided',
    led: 'Directed',
    created: 'Designed',
    built: 'Engineered',
    made: 'Produced',
    did: 'Executed',
  };
  return suggestions[weakVerb.toLowerCase()] || '';
}

// Hedging phrases, not verbs. Verb quality is handled by the strength tiers
// above; this list catches constructions that bury the actual contribution.
export const WEAK_WORDS = [
  'responsible for',
  'assisted with',
  'helped with',
  'helped out',
  'involved in',
  'participated in',
  'worked on',
  'contributed to',
  'familiar with',
  'exposure to',
  'some experience with',
  'basic knowledge of',
  'duties included',
  'tasked with',
] as const;

// Self-descriptions that claim a trait instead of showing evidence.
export const BUZZWORDS = [
  'team player',
  'hard-working',
  'hardworking',
  'detail-oriented',
  'self-starter',
  'go-getter',
  'results-driven',
  'results-oriented',
  'proven track record',
  'think outside the box',
  'dynamic',
  'synergy',
  'passionate about',
  'highly motivated',
] as const;

export const ATS_KEYWORDS = [
  'leadership',
  'strategy',
  'execution',
  'cross-functional',
  'stakeholder',
  'metrics',
  'kpi',
  'okr',
  'agile',
  'scrum',
  'sprint',
  'roadmap',
  'product',
  'engineering',
  'design',
  'marketing',
  'sales',
  'operations',
  'finance',
  'data',
  'analytics',
  'machine learning',
  'ai',
  'api',
  'cloud',
  'aws',
  'gcp',
  'azure',
  'react',
  'typescript',
  'python',
  'sql',
  'research',
  'internship',
  'volunteer',
  'hackathon',
  'teaching assistant',
  'lab',
  'budget',
  'training',
  'customer service',
  'event planning',
  'fundraising',
  'excel',
  'matlab',
  'spss',
  'figma',
  'canva',
  'teamwork',
  'communication',
] as const;

export const STOPWORDS = new Set([
  'the',
  'a',
  'an',
  'and',
  'or',
  'but',
  'in',
  'on',
  'at',
  'to',
  'for',
  'of',
  'with',
  'by',
  'from',
  'as',
  'is',
  'was',
  'were',
  'be',
  'been',
  'being',
  'have',
  'has',
  'had',
  'do',
  'does',
  'did',
  'will',
  'would',
  'could',
  'should',
  'may',
  'might',
  'must',
  'shall',
  'can',
  'need',
  'it',
  'its',
  'this',
  'that',
  'these',
  'those',
  'i',
  'me',
  'my',
  'myself',
  'we',
  'our',
  'ours',
  'ourselves',
  'you',
  'your',
  'yours',
  'yourself',
  'yourselves',
  'he',
  'him',
  'his',
  'himself',
  'she',
  'her',
  'hers',
  'herself',
  'they',
  'them',
  'their',
  'theirs',
  'themselves',
  'what',
  'which',
  'who',
  'whom',
  'whose',
  'where',
  'when',
  'why',
  'how',
  'all',
  'each',
  'few',
  'more',
  'most',
  'other',
  'some',
  'such',
  'no',
  'nor',
  'not',
  'only',
  'own',
  'same',
  'so',
  'than',
  'too',
  'very',
  'just',
  'also',
  'then',
  'now',
  'here',
  'there',
  'up',
  'out',
  'if',
  'about',
  'into',
  'through',
  'during',
  'before',
  'after',
  'above',
  'below',
  'between',
  'under',
  'again',
  'further',
  'once',
  'am',
  'are',
]);

// Hard skills commonly sought by ATS. Covers professional tooling plus the
// tools students actually use: stats packages, lab techniques, design and
// media tools, campus-job software.
export const HARD_SKILLS = [
  'python',
  'javascript',
  'typescript',
  'java',
  'c++',
  'c#',
  'go',
  'rust',
  'sql',
  'html',
  'css',
  'react',
  'vue',
  'angular',
  'svelte',
  'next.js',
  'node.js',
  'django',
  'fastapi',
  'flask',
  'spring',
  'express',
  'aws',
  'gcp',
  'azure',
  'docker',
  'kubernetes',
  'terraform',
  'jenkins',
  'github actions',
  'git',
  'github',
  'gitlab',
  'jira',
  'confluence',
  'notion',
  'figma',
  'sketch',
  'salesforce',
  'hubspot',
  'marketo',
  'tableau',
  'power bi',
  'looker',
  'excel',
  'sheets',
  'pivot tables',
  'mongodb',
  'postgresql',
  'mysql',
  'redis',
  'elasticsearch',
  'dynamodb',
  'tensorflow',
  'pytorch',
  'scikit-learn',
  'pandas',
  'numpy',
  'spark',
  'hadoop',
  'ansible',
  'puppet',
  'chef',
  'linux',
  'unix',
  'bash',
  'shell',
  'powershell',
  'agile',
  'scrum',
  'kanban',
  'lean',
  'six sigma',
  'seo',
  'sem',
  'google analytics',
  'mixpanel',
  'amplitude',
  'photoshop',
  'illustrator',
  'indesign',
  'after effects',
  'premiere',
  'sap',
  'oracle',
  'workday',
  'servicenow',
  'blockchain',
  'solidity',
  'ethereum',
  'web3',
  'graphql',
  'rest api',
  'grpc',
  'websocket',
  'kafka',
  'rabbitmq',
  'sqs',
  'pub/sub',
  'cypress',
  'jest',
  'mocha',
  'playwright',
  'selenium',
  'webpack',
  'vite',
  'rollup',
  'parcel',
  'esbuild',
  'tailwind',
  'bootstrap',
  'material ui',
  'chakra ui',
  'shadcn',
  'prisma',
  'sequelize',
  'typeorm',
  'mongoose',
  'openapi',
  'swagger',
  'postman',
  'insomnia',
  'cicd',
  'devops',
  'sre',
  'platform engineering',
  'machine learning',
  'deep learning',
  'nlp',
  'computer vision',
  'data science',
  'etl',
  'data pipeline',
  'data warehouse',
  'data lake',
  'dbt',
  'a/b testing',
  'user research',
  'ux research',
  'product analytics',
  'content strategy',
  'copywriting',
  'technical writing',
  'documentation',
  'event-driven',
  'microservices',
  'serverless',
  'lambda',
  'cloud functions',
  // Student and early-career tooling
  'matlab',
  'spss',
  'stata',
  'sas',
  'r',
  'latex',
  'canva',
  'powerpoint',
  'google sheets',
  'google docs',
  'google slides',
  'qualtrics',
  'nvivo',
  'arcgis',
  'autocad',
  'solidworks',
  'arduino',
  'raspberry pi',
  'labview',
  'wordpress',
  'squarespace',
  'wix',
  'mailchimp',
  'hootsuite',
  'capcut',
  'final cut',
  'davinci resolve',
  'unity',
  'unreal engine',
  'quickbooks',
  'bloomberg terminal',
  // Lab techniques
  'pcr',
  'gel electrophoresis',
  'western blot',
  'cell culture',
  'chromatography',
  'spectroscopy',
  'microscopy',
  'titration',
  'elisa',
];

export const SOFT_SKILLS = [
  'leadership',
  'communication',
  'project management',
  'problem solving',
  'collaboration',
  'critical thinking',
  'time management',
  'adaptability',
  'creativity',
  'emotional intelligence',
  'negotiation',
  'conflict resolution',
  'mentoring',
  'coaching',
  'delegation',
  'strategic thinking',
  'decision making',
  'analytical thinking',
  'attention to detail',
  'interpersonal skills',
  'teamwork',
  'cross-functional',
  'stakeholder management',
  'presentation',
  'public speaking',
  'facilitation',
  'workshop design',
  'customer empathy',
  'user-centered',
  'design thinking',
  'systems thinking',
  // Student and early-career strengths
  'event planning',
  'fundraising',
  'tutoring',
  'customer service',
  'peer mentoring',
  'community outreach',
  'recruitment',
  'onboarding',
];

export function extractSkills(text: string): { hard: string[]; soft: string[] } {
  const hard = HARD_SKILLS.filter((skill) => matchesTerm(text, skill));
  const soft = SOFT_SKILLS.filter((skill) => matchesTerm(text, skill));
  return { hard: [...new Set(hard)], soft: [...new Set(soft)] };
}
